@baseUrl =  http://localhost:3001
@token = Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2M2M1ZGUwZmJkM2M1MmVkM2I2YTFkNDYiLCJlbWFpbCI6ImlkZW50aXR5d0B0ZXN0LnJ1Iiwicm9sZSI6ImN1c3RvbWVyIiwiY2l0eSI6ItCc0L7RgdC60LLQsCIsImlhdCI6MTY3NDMzMzM0NywiZXhwIjoxNjc0MzkzMzQ3fQ.MUs4qTbzaBIbBfKoCKtVdr0mV8ZJpNcO8gLCgdMuGKY

POST {{baseUrl}}/api/auth/signup HTTP/1.1
Content-Type: application/json

{
  "name": "The Fish",
  "email": "identityw2@test.ru",
  "city": "Москва",
  "password": "123456",
  "role": "performer",
  "birthDate": "1990-12-24"
}
###

POST {{baseUrl}}/api/auth/signin HTTP/1.1
Content-Type: application/json

{
  "email": "identityw2@test.ru",
  "password": "123456"
}

###
