@baseUrl =  http://localhost:3001
@token = Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2M2JkYzE5ODE4YzFkMzMyYzY1N2ViNWEiLCJlbWFpbCI6ImlkZW50aXR5QHRlc3QucnUiLCJyb2xlIjoiY3VzdG9tZXIiLCJpYXQiOjE2NzMzODAyNDgsImV4cCI6MTY3MzM4MDMwOH0.DeGckvVTOh8AqH1uyrRxlPSlocWGUK9Nr3mEmbVugzQ

POST {{baseUrl}}/api/auth/signup HTTP/1.1
Content-Type: application/json

{
  "name": "The Keks",
  "email": "identity2@test.ru",
  "city": "Москва",
  "password": "123456",
  "role": "customer",
  "birthDate": "1990-12-24"
}
###

POST {{baseUrl}}/api/auth/signin HTTP/1.1
Content-Type: application/json

{
  "email": "identity2@test.ru",
  "password": "0123456"
}

###
