

@baseUrl =  http://localhost:3001
@token = Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2M2M0ODEyZjg4ZTlkZjUzOWViNTE1ODciLCJlbWFpbCI6ImlkZW50aXR5NEB0ZXN0LnJ1Iiwicm9sZSI6InBlcmZvcm1lciIsImNpdHkiOiLQnNC-0YHQutCy0LAiLCJpYXQiOjE2NzM5MTE3NTMsImV4cCI6MTY3Mzk3MTc1M30.VDViLoMhGAIncqa4X_pLfkhi73MFBYXwVioIJvtiYl0


GET {{baseUrl}}/api/users/63bdd579a1498bd4c39e868a HTTP/1.1
Authorization: {{token}}

###

PATCH {{baseUrl}}/api/users/password HTTP/1.1
Authorization: {{token}}
Content-Type: application/json

{
  "email": "identity2@test.ru",
  "password": "0123456",
  "newPassword": "0123456"
}
###

PATCH {{baseUrl}}/api/users HTTP/1.1
Authorization: {{token}}
Content-Type: application/json

{
  "name": "The New Cat",
  "city": "Санкт-Петербург",
  "birthDate": "2002-02-22"
}

###

POST {{baseUrl}}/api/users/avatars HTTP/1.1
Authorization: {{token}}
Content-Type: multipart/form-data; boundary=WebKitFormBoundary

--WebKitFormBoundary
Content-Disposition: form-data; name="avatar"; filename="avatar.png"
Content-Type: image/png

< ./1.png
--WebKitFormBoundary--

###


