@baseUrl =  http://localhost:3002
@token = Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2M2M1ZGUwZmJkM2M1MmVkM2I2YTFkNDYiLCJlbWFpbCI6ImlkZW50aXR5d0B0ZXN0LnJ1Iiwicm9sZSI6ImN1c3RvbWVyIiwiY2l0eSI6ItCc0L7RgdC60LLQsCIsImlhdCI6MTY3NDMzMzM0NywiZXhwIjoxNjc0MzkzMzQ3fQ.MUs4qTbzaBIbBfKoCKtVdr0mV8ZJpNcO8gLCgdMuGKY
@token2 = Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2M2NjNGUxYjU3ODUxZWU3YmNiZjRjZWYiLCJlbWFpbCI6ImlkZW50aXR5dzJAdGVzdC5ydSIsInJvbGUiOiJwZXJmb3JtZXIiLCJjaXR5Ijoi0JzQvtGB0LrQstCwIiwiaWF0IjoxNjc0MzMzNzMxLCJleHAiOjE2NzQzOTM3MzF9.CHKtTy52z8cC5cj6lINlea5eVJY4pnvi6kb6v5v8DzY

# Create a new task
POST {{baseUrl}}/api/tasks HTTP/1.1
Authorization: {{token}}
Content-Type: application/json

{
  "title": "Разработать калькулятор на JS 2",
  "description": "Разработать калькулятор на JS. Необходим простой калькулятор с базовыми операциями (сложение, вычитание, умножение, деление). Результат предоставить ввиде ссылки на гитхаб-репозиторий",
  "categoryId": 1,
  "category": 1,
  "price": 5000,
  "deadline": "2023-03-12",
  "address": "Москва, ул. Сельскохозяйственная",
  "tags": [1, 2],
  "userId": "63bdd579a1498bd4c39e868a"
}

###

# Get task by id
GET {{baseUrl}}/api/tasks/1 HTTP/1.1

###

# Get all tasks
GET {{baseUrl}}/api/tasks?sort=responses HTTP/1.1
Authorization: {{{{token2}}}}
###


# Get my tasks
GET {{baseUrl}}/api/tasks/my HTTP/1.1
Authorization: {{token}}
###

# Take response
POST {{baseUrl}}/api/tasks/3/response HTTP/1.1
Authorization: {{token2}}
###

# Cancel task
POST {{baseUrl}}/api/tasks/1/cancel HTTP/1.1
Authorization: {{token2}}
###

# Progress task
POST {{baseUrl}}/api/tasks/3/progress HTTP/1.1
Authorization: {{token}}
Content-Type: application/json

{
  "performerId": "63c446e1cbac5364d96a2195"
}
###

# Done task
POST {{baseUrl}}/api/tasks/3/done HTTP/1.1
Authorization: {{token}}

###

# Failed task
POST {{baseUrl}}/api/tasks/3/failed HTTP/1.1
Authorization: {{token2}}

###

# Upload Image
POST {{baseUrl}}/api/tasks/1/image
Authorization: {{token}}
Content-Type: multipart/form-data; boundary=Upload

--Upload
Content-Disposition: form-data; name="file"; filename="1.png"
Content-Type: image/png

< ./1.png
--Upload--

###
